### ISSUE TITLE
Error detecting Command string same start

### ISSUE THREAD

**Issue by CentauriDK** [Erriez/ErriezSerialTerminal#9]
I have discovered a little errorin the comparison of the command string.
It's like it takes the first that matches part of the string.

I have the following commands but the code always runs it's like i entered the first command "Setting_Ind_Bom"
so both "Setting_Ind_Port" and "Setting_Ind_Vejslojfe" get detected as "Setting_Ind_Bom"

  term.addCommand("Setting_Ind_Bom", cmd_Setting_Ind_Bom);
  term.addCommand("Setting_Ind_Port", cmd_Setting_Ind_Port);
  term.addCommand("Setting_Ind_Vejslojfe", cmd_Setting_Ind_Vejslojfe);

**Comment by CentauriDK** [comment]
Sorry found out i had to increace the command chars witch is standard 8.

#define ST_NUM_COMMAND_CHARS    8

Thanks Kim.

**Comment by Erriez** [comment]
Thanks for using my library. Good to hear you found a solution by configuring macro `ST_NUM_COMMAND_CHARS`.
